import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Navbar2 from "./components/Navbar2";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Te Fare Mo'a - Academia de Danzas Polinesias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preload" href="/fonts/aloha.otf" as="font" type="font/otf"  />
        <link rel="preload" href="/fonts/aloha.otf" as="font" type="font/otf"  />
        <link rel="preload" href="/fonts/oswald.ttf" as="font" type="font/ttf" />
        <link rel="preload" href="/fonts/adorage.ttf" as="font" type="font/ttf" />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />        
      </body>
    </html>
  );
}
